server:
  port: 8585
  servlet:
    context-path: /spt-api

spring:
  profiles:
    active: dev
  application:
    name: spring-practice-tasks
  datasource:
    url: jdbc:postgresql://localhost:5555/practice_tasks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: org.example.spring_practice_tasks.impl.model.kafka
    producer:
      group-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3

    listener:
      log-container-config: false

kafka:
  topic:
    notes:
      name: note-events
      partitions: 3
      replicas: 1
    notes-dlt:
      name: note-events.DLT

logging:
  pattern:
    console:
      "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId}] %-5level - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        kafka: WARN
        security: DEBUG
      apache:
        kafka: WARN
    kafka: WARN



management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: spring-practice-tasks